// <auto-generated />
namespace DayThree_FinancialPortal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddedInvites : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedInvites));
        
        string IMigrationMetadata.Id
        {
            get { return "201810301706307_AddedInvites"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
